# Generated by Django 3.1.4 on 2020-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facemask_detectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageCollection',
        ),
    ]
